services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"      # RabbitMQ messaging port
      - "15672:15672"    # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}      # Use environment variables for credentials
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq   # Persist RabbitMQ data

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"     # Expose MongoDB on default port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}  # Use environment variables for security
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db   # Persist MongoDB data

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"            # Expose Mongo Express on port 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}  # Use the same root username
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}  # Use the same root password
      ME_CONFIG_BASICAUTH: true         # Enable basic authentication
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
  
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 30    # Check every 30 seconds
      KEEP_HISTORY: 1                    # Keep historical reports
    ports:
      - "5050:5050"                      # Allure Service UI port
    user: "${UID}:${GID}"                 # Set user to match host user (optional)
    volumes:
      - ./allure-results:/app/allure-results:rw # Mount volumes with restricted permissions
      - ./allure-reports:/app/default-reports:rw

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"  # Allure service API URL
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"                      # Allure UI port
    user: "${UID}:${GID}"                 # Set user to match host user (optional)
    
volumes:
  mongo-data:                     # Volume for MongoDB data
  rabbitmq-data:                  # Volume for RabbitMQ data
  allure-results:                 # Volume for allure-results
  allure-reports:                 # Volume for allure-reports
