name: Tests

on: 
  repository_dispatch:
    types: [ deployment-completed-event ]
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.11"
        os:
          - ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0s

    - name: Setup python for test ${{ matrix.py }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}

    - name: Update pip
      run: pip install --upgrade pip

    - name: Install dependencies
      run: |
        sudo apt install make
        pip install pipenv
        pip install tox tox-gh-actions
    
    - name: Install uaf package to pipenv environment
      run: pipenv install .
    
    - name: Setup test suite
      run: tox r -e py${{ matrix.py }} -vv --notest
    
    - name: Decrypt configs
      run: make decrypt security_key=${{ secrets.SECURITY_KEY }}
    
    - name: Run test suite
      run: tox r -e py${{ matrix.py }}
      env:
        CI_RUN: "yes"
        DIFF_AGAINST: HEAD