name: Tests

on: 
  repository_dispatch:
    types: [ deployment-completed-event ]
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.11"
        os:
          - ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install self-tox
      run: python -m pip install .
    - name: Setup python for test ${{ matrix.py }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}
    - name: Install pipenv for test ${{ matrix.py }}
      run: pip install pipenv 
    - name: Setup make
      run: sudo apt install make
    - name: Decrypt configs
      run: pipenv run python cli.py --mode decrypt --key ${{ secrets.SECURITY_KEY }} --data_file configs/test/common.yml
    - name: Setup test suite
      run: tox r -e py${{ matrix.py }} -vv --notest
    - name: Run test suite
      run: tox r -e py${{ matrix.py }}
      env:
        CI_RUN: "yes"
        DIFF_AGAINST: HEAD